### ISSUE TITLE
Dockerimage: Model is kept in vram after transcription

### ISSUE THREAD

**Issue by Deathproof76** [JSchmie/ScrAIbe#29]
Hallo nochmal und vielen Dank übrigens fürs coole Projekt😊

Using the small whisper model and "Auto Transcribe" needs almost 11gb of Vram. After transcription and diarization is done the model seems to be kept in vram at 11gb Vram. As a "GPU Poor" person I ask: Would it be possible to flush it automatically after use? is there also a way to set beam size maybe?

edit: this is weird, small uses about 11gb of vram, medium about 9gb and large uses 11gb of vram. Does it batch, or maybe share ram?

Btw: There are a few other projects with way less user friendly webuis/or just api that use [faster-whisper](https://github.com/SYSTRAN/faster-whisper) or [insanely-fast-whisper ](https://github.com/Vaibhavs10/insanely-fast-whisper) that need less vram and are also faster.  Mostly by using [ctranslate](https://github.com/OpenNMT/CTranslate2), [batching](https://github.com/Blair-Johnson/batch-whisper), [bettertransformer](https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#bettertransformer), [flashattention-2](https://huggingface.co/docs/transformers/main/en/perf_infer_gpu_one#flashattention-2), or [whisper-distil models](https://huggingface.co/distil-whisper/distil-large-v2) ([also german](https://huggingface.co/sanchit-gandhi/distil-whisper-large-v3-de-kd)).

I've already used [whisper-asr-webservice](https://github.com/ahmetoner/whisper-asr-webservice) which currently doesn't have diarization but tries to implement it via [whisperx ](https://github.com/m-bain/whisperX) and [wordcab-transcribe](https://github.com/Wordcab/wordcab-transcribe) which uses [Nvidia NeMo for diarization](https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb). Maybe some of these ressources are of use to you? 

I've no serious programming knowledge, I just dabble a little bit. I just really like your concept of the webui. I actually tried something similar with a simple gradio interface half a year ago which transcribes, diarizes via the wordcab-transcribe api and also formats the .json and associates names. It  But it never worked as robustly as I hoped and I stopped working on it due to missing time and programming knowledge. Forgive me for this wall of text, I'm just a little bit excited about the possibilities and really glad I found your project😄

![Screenshot 2024-01-02 214458](https://github.com/JSchmie/ScrAIbe/assets/95944496/c33b2ccb-be8f-4235-852b-130fc81c877f)

via the wordcab-api it used about 4gb of Vram with spike of 10gb for the first 20 seconds (probably due to diarization) with the largev2 model and took about 2:30 min for a 22min file
![Screenshot 2024-01-02 215730](https://github.com/JSchmie/ScrAIbe/assets/95944496/6ca88ccc-f0ff-4ed6-9fc9-16963a672359)
so maybe there's some room for improvement? 

I also tried via [insanely-fast-whisper ](https://github.com/Vaibhavs10/insanely-fast-whisper) which simply uses multiple optimizations and it took about 33 seconds (same file only transcription task, segmenting added about 1:20min) with less than 8gb vram. 150min of audio in less than 5 minutes transcription + diarization (have to recheck the exact time/usage).

**Comment by JSchmie** [comment]
There will be a new release quite soon where you can remove the model after using it and many other optimization options. So stay tuned. 
regarding your edit, this will be fixed in the next version. 
I know about the fast methods, but currently the plan is not to support every whisper model out there. The product aims to be robust, and therefore I am willing to take the slower model. But I agree that there is space for improvement and I want to try to implement other models if they are robust and maintained. 
First, I would like to try to use model quantization to allow a good performance on CPU.
